### ISSUE TITLE
Case Functions example's output differs from what is stated

### ISSUE THREAD

**Issue by tocic** [uni-algo/uni-algo#20]
When testing the following example from the README

```cpp
#include <uni_algo/case.h>
#include <uni_algo/conv.h>

#include <algorithm>
#include <iostream>
#include <random>
#include <string>
#include <vector>

int main() {
  // Use the Makedonian alphabet for example
  std::u32string str32 = U"абвгдѓежзѕијклљмнњопрстќуфхцчџшАБВГДЃЕЖЗЅИЈКЛЉМНЊОПРСТЌУФХЦЧЏШ";

  std::vector<std::string> vec8;
  for (char32_t c : str32) {  // Convert the code points to a vector of UTF-8 code units
    vec8.emplace_back(una::utf32to8(std::u32string(1, c)));
  }
  std::shuffle(vec8.begin(), vec8.end(), std::mt19937(42));  // Shuffle them just in case

  // For example sort them with the binary comparison first
  std::sort(vec8.begin(), vec8.end());

  // Output: ЃЅЈЉЊЌЏАБВГДЕЖЗИКЛМНОПРСТУФХЦЧШабвгдежзиклмнопрстуфхцчшѓѕјљњќџ
  // Everything is out of place

  // Sort them with una::casesens::utf8_collate
  std::sort(vec8.begin(), vec8.end(), [](auto a, auto b) {
    return una::casesens::collate_utf8(a, b) < 0;
  });

  std::for_each(vec8.begin(), vec8.end(), [](auto s) { std::cout << s; });
  std::cout << '\n';

  // Output: аАбБвВгГдДѓЃеЕжЖзЗѕЅиИјЈкКлЛљЉмМнНњЊоОпПрРсСтТќЌуУфФхХцЦчЧџЏшШ
  // This is the correct order for the Makedonian alphabet
}
```

I got `аАбБвВгГѓЃдДеЕжЖзЗѕЅиИјЈкКќЌлЛљЉмМнНњЊоОпПрРсСтТуУфФхХцЦчЧџЏшШ` which is different from the output stated in the last comment.

```diff
comment
< аАбБвВгГдДѓЃеЕжЖзЗѕЅиИјЈкКлЛљЉмМнНњЊоОпПрРсСтТќЌуУфФхХцЦчЧџЏшШ
---
my
> аАбБвВгГѓЃдДеЕжЖзЗѕЅиИјЈкКќЌлЛљЉмМнНњЊоОпПрРсСтТуУфФхХцЦчЧџЏшШ
```

Compiled on Linux with `gcc (GCC) 12.2.1`, tried to execute with both `LC_ALL=en_US.UTF-8` and `LC_ALL=mk_MK.UTF-8`. Previous examples work fine.

**Comment by mg152** [comment]
Ah, I see what's the problem here. It's not in the function but in the example.
This function uses fast but very simple collation algorithm that is locale-independent but Macedonian language is locale-dependent because `Ѓ` and `Ќ` letters require reordering.

I checked other Cyrillic languages and Macedonian and Kazakh literally the only two that in common use and require reordering. So I just didn't notice that.

Nothing much I can do, the algorithm just doesn't produce good result for some languages by design. I'll fix the example by using some other alphabet that works.

**Comment by mg152** [comment]
Done in commit 3a27b09ca8e1edf9e0bcdbba3fa2e6aa1dab2929
