### ISSUE TITLE
Can't check the signature of the 1.2.0 tag

### ISSUE THREAD

**Issue by tocic** [uni-algo/uni-algo#36]
I just want to make sure that you intentionally changed the signing key for the 1.2.0 tag. I can't verify it with the old one:

```bash
git clone https://github.com/uni-algo/uni-algo && cd uni-algo
git verify-tag v1.1.0 # Good signature from "mg152 <mg152git@gmail.com>"
git verify-tag v1.2.0 # Can't check signature: No public key
```

**Comment by mg152** [comment]
Yeah, I somehow forgot the passphrase to my old key so commits/tags signed with different GPG key now starting with commit ab58edc8aaf09a177e84369765fcaaf70a412767.

Fun facts: I have my passphrase written in a safe place but it seems I wrote it wrong. I even did write a bash script to try to brute force it because I typed it like every day for a year with my muscle memory so I remember the part of the keyboard I used, it was like super simple combination. But no luck again. I wasted like a day for all that crap. This is like the most mysterious thing that happened to me recently.
