### ISSUE TITLE
Suggestion: improving the directory structure

### ISSUE THREAD

**Issue by danilshvalov** [uni-algo/uni-algo#4]
Hi! Thank you for this amazing library! I have a suggestion to improve it.

I think it would be better if you use a more typical library structure. Other libraries use directories to structure headers. I suggest doing the same. I also suggest naming the header directory as `include` instead of `src`.

<details>
<summary>Example of a structure</summary>

```
include
└── uni
    ├── all.h
    ├── break_grapheme.h
    ├── break_word.h
    ├── case.h
    ├── config.h
    ├── convert.h
    ├── ext
    │   └── translit
    │       ├── japanese_kana_to_romaji_hepburn.h
    │       └── macedonian_to_latin_docs.h
    ├── impl
    │   ├── LICENSE.txt
    │   ├── break_grapheme.h
    │   ├── break_grapheme_data.h
    │   ├── break_grapheme_data_extern.h
    │   ├── break_word.h
    │   ├── break_word_data.h
    │   ├── break_word_data_extern.h
    │   ├── case.h
    │   ├── case_data.h
    │   ├── case_data_extern.h
    │   ├── case_locale.h
    │   ├── convert.h
    │   ├── cpp_lib_version.h
    │   ├── doc
    │   │   ├── README_FIRST.txt
    │   │   ├── config_defines.txt
    │   │   ├── generator_utf16.txt
    │   │   ├── list_and_info.txt
    │   │   ├── signature.txt
    │   │   └── what_is_this_language.txt
    │   ├── example
    │   │   └── cpp_proxy_iterator.h
    │   ├── iterator.h
    │   ├── norm.h
    │   ├── norm_data.h
    │   ├── norm_data_extern.h
    │   ├── types.h
    │   └── unicode_version.h
    ├── internal
    │   ├── defines.h
    │   ├── error.h
    │   ├── sentinel.h
    │   ├── stages.h
    │   └── undefs.h
    ├── iterator.h
    ├── norm.h
    ├── ranges.h
    └── version.h
```

</details>

<details>
<summary>Example of libraries</summary>

- [`fmtlib`](https://github.com/fmtlib/fmt)
- [`spdlog`](https://github.com/gabime/spdlog)
- [`Boost.Asio`](https://github.com/boostorg/asio) (and other boost libraries)
- [`nlohmann/json`](https://github.com/nlohmann/json)
- [`googletest`](https://github.com/google/googletest/tree/main/googletest)

</details>

In the code it will look like this:

```cpp
#include <uni/all.h>

int main() {
    // ...
}
```
I can help with the implementation of this change.

**Comment by mg152** [comment]
Thanks for the suggestion. Actually it is not that simple as it might look so I want to discuss it.

At the moment I'm thinking about two approaches:
1. Leave it as is but maybe rename prefix to `uni_algo_*` instead of `cpp_uni_*` so the usage will be
```#include <uni_algo_all.h>```
2. Or use a subdirectory as you proposed
```#include <uni_algo/all.h>```

It's probably not that important it can be easily handled by `CMakeLists.txt`

And about the directory structure inside the repository that is the complex part.
If I rename `src` to `include` I will be forced to split the source code into 2 directories `include` and `src` where `src` will contain only 1 file `cpp_uni_data.cpp` it's just awkward and I want to avoid it because of many reasons. The most important that right now the library itself is `src` directory other dirs are irrelevant and splitting it will create more mess.

So I open to suggestions what might be the best approach.
For everyone reading this please participate in the discussion I want to deal with this sooner than later.

**Comment by danilshvalov** [comment]
I'm not sure if you need to have `.cpp` files.  In #5, I changed the `.cpp` file to `.h`, so now you shouldn't have the `src/` directory.

**Comment by mg152** [comment]
Including Unicode data into `.h` files by default is no go. It just makes compilation slower and gains nothing.

I plan to add constexpr mode where the library will be header-only (just a side effect of constexpr) but it won't be used by default.
Also I plan to add support for C++20 modules so there will be additional file `cpp_uni_modules.ixx` or whatever it will be called that is a source file that must be compiled so `include` directory is not a place for such file.

I cannot get rid of `src` directory no matter what. As I said it's not that simple as it looks.

Also do not make pull requests that change the library code for now I won't be able to accept them the problem is at the moment the library is around 50-70% I already implemented and right now I test and add those things bit by bit. So you just wasting your time by changing things that will be changed anyway.
And if you want to show me something do not make a pull request just make a change in your forked repo and show me.

I'll add `PULL_REQUEST_TEMPLATE.md` a bit later so people won't waste their time.

**Comment by mg152** [comment]
After some thinking I decided I'll use the most common approach almost the same you proposed it just works better with CMake and what people are familiar with. So I'll split `src` to `src` and `include` and cope with it somehow.

The usage will be:
```cpp
#include <uni_algo/all.h>
```
And compile `src/data.cpp`

For people that want header-only I plan this: https://github.com/uni-algo/uni-algo/issues/11

Everything should be done within a couple of weeks.

**Comment by mg152** [comment]
Done in commits e00648c3fc173493b12a3f287eb91ab9c398a9a8...ddddb1f942411dd70f344f8a8c172427e1e89283
